package kconfig

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// End-to-end coverage for leaf objects whose source is produced by a Kbuild
// rule rather than checked in.
//
// These tests deliberately call tree.CompactMetadataBatchWithOptions directly
// instead of compactMetadataBatchWithOptionsForTest. That helper fabricates a
// source file for every object that does not resolve on disk, which is exactly
// the condition under test: with it, lib/raid6/int1.o silently acquires an
// int1.c and the bug never fires.

// generatedSourceMetadata builds a synthetic tree on disk, parses it the way
// the real tool does, and resolves compact metadata for one config.
func generatedSourceMetadata(
	t *testing.T,
	kconfigText string,
	files map[string]string,
	srcarch string,
	flags map[string]string,
) (*CompactMetadata, *CompactConfig, string) {
	t.Helper()
	tree := mustParseString(t, kconfigText)
	root := t.TempDir()
	for name, contents := range files {
		mustWriteSource(t, root, name, contents)
	}
	writeCompactContentGraphForcedInputs(t, root)

	kb, err := ParseKbuildDirectoryTree(filepath.Join(root, "Makefile"), KbuildOptions{RootDir: root})
	if err != nil {
		t.Fatalf("ParseKbuildDirectoryTree() failed: %v", err)
	}
	metadata, err := tree.CompactMetadataBatchWithOptions(
		[]NamedConfig{{Name: "test", Flags: flags}},
		CompactMetadataOptions{
			SourceRoot:            root,
			Srcarch:               srcarch,
			CompileEnvironmentABI: "generated-source-abi-v1",
		},
		func(*ResolvedConfig) (CompactConfigGraph, error) {
			return CompactConfigGraph{Kbuild: kb, GeneratedHeadersLabel: "//headers:test"}, nil
		},
	)
	if err != nil {
		t.Fatalf("CompactMetadataBatchWithOptions() failed: %v", err)
	}
	return metadata, configByName(metadata, "test"), root
}

// TestCompactMetadataResolvesRaid6UnrolledSources covers the reported failure
// on 6.12: raid6 selects int{1,2,4,8}.o, whose sources are generated by a
// pattern rule from a single ".uc" template, and graph generation used to abort
// with "exact input scan cannot resolve a source for leaf object".
func TestCompactMetadataResolvesRaid6UnrolledSources(t *testing.T) {
	metadata, config, _ := generatedSourceMetadata(t, "mainmenu \"raid6\"\n", map[string]string{
		"Makefile": "obj-y += lib/raid6/\n",
		"lib/raid6/Makefile": `obj-y += raid6_pq.o
raid6_pq-y += int1.o int2.o tables.o
hostprogs += mktables

quiet_cmd_unroll = UNROLL  $@
      cmd_unroll = $(AWK) -v N=$* -f $(src)/unroll.awk < $< > $@

targets += int1.c int2.c
$(obj)/int%.c: $(src)/int.uc $(src)/unroll.awk FORCE
	$(call if_changed,unroll)

quiet_cmd_mktable = TABLE   $@
      cmd_mktable = $(obj)/mktables > $@
targets += tables.c
$(obj)/tables.c: $(obj)/mktables FORCE
	$(call cmd,mktable)
`,
		"lib/raid6/int.uc":     "/* raid6 template */\n",
		"lib/raid6/unroll.awk": "# unroll v1\n",
		"lib/raid6/mktables.c": "#include <stdio.h>\nint main(void) { return 0; }\n",
		// The generated tables.c includes these; the host program's own
		// includes are deliberately not scanned.
		"include/linux/export.h":  "\n",
		"include/linux/raid/pq.h": "\n",
	}, "x86", nil)

	for _, tc := range []struct {
		object          string
		generatedSource string
		source          string
		generator       string
		args            []string
		inputs          []string
	}{
		{
			object:          "lib/raid6/int1.o",
			generatedSource: "lib/raid6/int1.c",
			source:          "lib/raid6/int.uc",
			generator:       "raid6_unroll",
			args:            []string{"-n", "1"},
			inputs:          []string{"lib/raid6/int.uc"},
		},
		{
			object:          "lib/raid6/int2.o",
			generatedSource: "lib/raid6/int2.c",
			source:          "lib/raid6/int.uc",
			generator:       "raid6_unroll",
			args:            []string{"-n", "2"},
			inputs:          []string{"lib/raid6/int.uc"},
		},
		{
			// RAID6 does not link without tables.o. Its generator reads
			// nothing, so the hostprog source stands for the object.
			object:          "lib/raid6/tables.o",
			generatedSource: "lib/raid6/tables.c",
			source:          "lib/raid6/mktables.c",
			generator:       "raid6_mktables",
		},
	} {
		t.Run(tc.object, func(t *testing.T) {
			variant := variantByTarget(metadata, objectTarget(metadata, config, tc.object))
			if variant.GeneratedSource != tc.generatedSource {
				t.Errorf("generated_source = %q, want %q", variant.GeneratedSource, tc.generatedSource)
			}
			// Source keeps naming a checked-in file: the repository rule
			// requires an object's source to exist in the tree.
			if variant.Source != tc.source {
				t.Errorf("source = %q, want %q", variant.Source, tc.source)
			}
			if variant.Generator != tc.generator {
				t.Errorf("generator = %q, want %q", variant.Generator, tc.generator)
			}
			if strings.Join(variant.GeneratorArgs, " ") != strings.Join(tc.args, " ") {
				t.Errorf("generator_args = %v, want %v", variant.GeneratorArgs, tc.args)
			}
			if strings.Join(variant.GeneratorInputs, " ") != strings.Join(tc.inputs, " ") {
				t.Errorf("generator_inputs = %v, want %v", variant.GeneratorInputs, tc.inputs)
			}
		})
	}

	// int1.o and int2.o differ only in unroll factor, so they must not share
	// an identity or collapse into one action.
	first := variantByTarget(metadata, objectTarget(metadata, config, "lib/raid6/int1.o"))
	second := variantByTarget(metadata, objectTarget(metadata, config, "lib/raid6/int2.o"))
	if first.ContentID == second.ContentID {
		t.Errorf("int1.o and int2.o share content ID %q", first.ContentID)
	}
	if compactConcreteRecipeID(first) == compactConcreteRecipeID(second) {
		t.Errorf("int1.o and int2.o share an action recipe")
	}
}

// TestCompactMetadataDigestsRaid6UnrollScript pins that unroll.awk invalidates
// the object even though the action never reads it: internal/cmd/unroll stands
// in for it, so only a digest-only footprint entry can catch a change.
func TestCompactMetadataDigestsRaid6UnrollScript(t *testing.T) {
	files := map[string]string{
		"Makefile": "obj-y += lib/raid6/\n",
		"lib/raid6/Makefile": `obj-y += int1.o

quiet_cmd_unroll = UNROLL  $@
      cmd_unroll = $(AWK) -v N=$* -f $(src)/unroll.awk < $< > $@
$(obj)/int%.c: $(src)/int.uc $(src)/unroll.awk FORCE
	$(call if_changed,unroll)
`,
		"lib/raid6/int.uc":     "/* raid6 template */\n",
		"lib/raid6/unroll.awk": "# unroll v1\n",
	}

	metadata, config, _ := generatedSourceMetadata(t, "mainmenu \"raid6\"\n", files, "x86", nil)
	before := variantByTarget(metadata, objectTarget(metadata, config, "lib/raid6/int1.o"))
	inputs, err := metadata.expandedSourceInputGroup(before.SourceInputGroup, "raid6 int1")
	if err != nil {
		t.Fatalf("expand raid6 source inputs: %v", err)
	}
	for _, want := range []string{"lib/raid6/int.uc", "lib/raid6/unroll.awk"} {
		if got := sourceInputByPath(inputs, want).Path; got == "" {
			t.Fatalf("raid6 source inputs %v are missing %q", inputs, want)
		}
	}

	files["lib/raid6/unroll.awk"] = "# unroll v2\n"
	changed, changedConfig, _ := generatedSourceMetadata(t, "mainmenu \"raid6\"\n", files, "x86", nil)
	after := variantByTarget(changed, objectTarget(changed, changedConfig, "lib/raid6/int1.o"))
	if after.ContentID == before.ContentID {
		t.Fatalf("changing unroll.awk did not change content ID %q", before.ContentID)
	}
}

// TestCompactMetadataResolvesX86Poly1305Perlasm covers the other reported
// failure: 6.12's arch/x86/crypto pattern rule generating a ".S" from a ".pl".
func TestCompactMetadataResolvesX86Poly1305Perlasm(t *testing.T) {
	metadata, config, _ := generatedSourceMetadata(t, "mainmenu \"poly1305\"\n", map[string]string{
		"Makefile": "obj-y += arch/x86/crypto/\n",
		"arch/x86/crypto/Makefile": `obj-y += poly1305-x86_64.o
poly1305-x86_64-y := poly1305-x86_64-cryptogams.o poly1305_glue.o
targets += poly1305-x86_64-cryptogams.S

quiet_cmd_perlasm = PERLASM $@
      cmd_perlasm = $(PERL) $< > $@
$(obj)/%.S: $(src)/%.pl FORCE
	$(call if_changed,perlasm)
`,
		"arch/x86/crypto/poly1305-x86_64-cryptogams.pl": "# perlasm v1\n",
		"arch/x86/crypto/poly1305_glue.c":               "int poly1305_glue;\n",
	}, "x86", nil)

	variant := variantByTarget(metadata, objectTarget(metadata, config, "arch/x86/crypto/poly1305-x86_64-cryptogams.o"))
	if want := "arch/x86/crypto/poly1305-x86_64-cryptogams.S"; variant.GeneratedSource != want {
		t.Errorf("generated_source = %q, want %q", variant.GeneratedSource, want)
	}
	if want := "arch/x86/crypto/poly1305-x86_64-cryptogams.pl"; variant.Source != want {
		t.Errorf("source = %q, want %q", variant.Source, want)
	}
	if variant.Generator != "perl_stdout" {
		t.Errorf("generator = %q, want perl_stdout", variant.Generator)
	}
	if len(variant.GeneratorArgs) != 0 {
		t.Errorf("generator_args = %v, want none", variant.GeneratorArgs)
	}
	// The generated target is assembly even though the source is a ".pl".
	if got := compactSourceLanguage(compactCompiledSourcePath(variant)); got != "asm" {
		t.Errorf("compiled language = %q, want asm", got)
	}
}

// TestCompactMetadataArm64PerlasmPrefersExplicitRule is the case the hardcoded
// object table gets wrong on 6.12: a pattern rule plus an explicit rule
// overriding it for one target. GNU make prefers the explicit rule, so
// sha256-core.S must come from sha512-armv8.pl, and the two objects must not
// collapse into one action despite sharing every other field.
func TestCompactMetadataArm64PerlasmPrefersExplicitRule(t *testing.T) {
	metadata, config, _ := generatedSourceMetadata(t, "mainmenu \"arm64 crypto\"\n", map[string]string{
		"Makefile": "obj-y += arch/arm64/crypto/\n",
		"arch/arm64/crypto/Makefile": `obj-y += sha256-core.o sha512-core.o

quiet_cmd_perlasm = PERLASM $@
      cmd_perlasm = $(PERL) $(<) void $(@)

$(obj)/%-core.S: $(src)/%-armv8.pl
	$(call cmd,perlasm)

$(obj)/sha256-core.S: $(src)/sha512-armv8.pl
	$(call cmd,perlasm)
`,
		"arch/arm64/crypto/sha512-armv8.pl": "# perlasm v1\n",
		"arch/arm64/kernel/vdso/.keep":      "\n",
		"arch/arm64/kernel/vdso32/.keep":    "\n",
	}, "arm64", nil)

	sha256 := variantByTarget(metadata, objectTarget(metadata, config, "arch/arm64/crypto/sha256-core.o"))
	sha512 := variantByTarget(metadata, objectTarget(metadata, config, "arch/arm64/crypto/sha512-core.o"))

	for _, tc := range []struct {
		name    string
		variant CompactObjectVariant
		target  string
	}{
		{name: "sha256", variant: sha256, target: "arch/arm64/crypto/sha256-core.S"},
		{name: "sha512", variant: sha512, target: "arch/arm64/crypto/sha512-core.S"},
	} {
		if tc.variant.GeneratedSource != tc.target {
			t.Errorf("%s generated_source = %q, want %q", tc.name, tc.variant.GeneratedSource, tc.target)
		}
		// Both come from sha512-armv8.pl: sha256 through the explicit
		// override, sha512 through the pattern rule.
		if want := "arch/arm64/crypto/sha512-armv8.pl"; tc.variant.Source != want {
			t.Errorf("%s source = %q, want %q", tc.name, tc.variant.Source, want)
		}
		if tc.variant.Generator != "perl_arg_out" {
			t.Errorf("%s generator = %q, want perl_arg_out", tc.name, tc.variant.Generator)
		}
		if strings.Join(tc.variant.GeneratorArgs, " ") != "void" {
			t.Errorf("%s generator_args = %v, want [void]", tc.name, tc.variant.GeneratorArgs)
		}
	}

	// Same source, flags and arguments; only the generated target differs.
	// Without the generator fields in both hashes these would be one action.
	if sha256.ContentID == sha512.ContentID {
		t.Errorf("arm64 sha256-core.o and sha512-core.o share content ID %q", sha256.ContentID)
	}
	if compactConcreteRecipeID(sha256) == compactConcreteRecipeID(sha512) {
		t.Errorf("arm64 sha256-core.o and sha512-core.o share an action recipe")
	}
}

// TestCompactMetadataReportsUnimplementedGenerator pins that a rule this
// project cannot run reports the Makefile line rather than the old opaque
// "cannot resolve a source" error. This is the shape 6.18 uses for mips and
// riscv poly1305, whose scripts spawn an "*-xlate.pl" child.
func TestCompactMetadataReportsUnimplementedGenerator(t *testing.T) {
	tree := mustParseString(t, "mainmenu \"unsupported generator\"\n")
	root := t.TempDir()
	for name, contents := range map[string]string{
		"Makefile": "obj-y += lib/crypto/\n",
		"lib/crypto/Makefile": `obj-y += poly1305-core.o

quiet_cmd_perlasm_poly1305 = PERLASM $@
      cmd_perlasm_poly1305 = $(PERL) $< 64 $@
$(obj)/poly1305-core.S: $(src)/poly1305-riscv.pl FORCE
	$(call if_changed,perlasm_poly1305)
`,
		"lib/crypto/poly1305-riscv.pl": "# perlasm\n",
	} {
		mustWriteSource(t, root, name, contents)
	}
	writeCompactContentGraphForcedInputs(t, root)

	kb, err := ParseKbuildDirectoryTree(filepath.Join(root, "Makefile"), KbuildOptions{RootDir: root})
	if err != nil {
		t.Fatalf("ParseKbuildDirectoryTree() failed: %v", err)
	}
	_, err = tree.CompactMetadataBatchWithOptions(
		[]NamedConfig{{Name: "test"}},
		CompactMetadataOptions{
			SourceRoot:            root,
			Srcarch:               "riscv",
			CompileEnvironmentABI: "generated-source-abi-v1",
		},
		func(*ResolvedConfig) (CompactConfigGraph, error) {
			return CompactConfigGraph{Kbuild: kb, GeneratedHeadersLabel: "//headers:test"}, nil
		},
	)
	if err == nil {
		t.Fatalf("CompactMetadataBatchWithOptions() succeeded, want an unimplemented-generator error")
	}
	for _, want := range []string{
		"no generator is implemented for leaf object",
		"lib/crypto/poly1305-core.o",
		"cmd_perlasm_poly1305",
		"canonical: PERL $< 64 $@",
		"internal/kconfig/generated_source_kinds.go",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error is missing %q\nerror: %v", want, err)
		}
	}
}

// TestCompactMetadataLeavesCheckedInSourcesAlone pins that the rule lookup runs
// only on the on-disk probe's miss path. An object with a real source must not
// be re-resolved through a rule, even when a pattern rule in the same directory
// could match it.
func TestCompactMetadataLeavesCheckedInSourcesAlone(t *testing.T) {
	metadata, config, _ := generatedSourceMetadata(t, "mainmenu \"mixed\"\n", map[string]string{
		"Makefile": "obj-y += arch/x86/crypto/\n",
		"arch/x86/crypto/Makefile": `obj-y += aesni-intel.o glue.o

quiet_cmd_perlasm = PERLASM $@
      cmd_perlasm = $(PERL) $< > $@
$(obj)/%.S: $(src)/%.pl FORCE
	$(call if_changed,perlasm)
`,
		// aesni-intel has both a checked-in ".S" and a ".pl" the pattern rule
		// would match. The checked-in source wins.
		"arch/x86/crypto/aesni-intel.S":  "/* asm */\n",
		"arch/x86/crypto/aesni-intel.pl": "# perlasm\n",
		"arch/x86/crypto/glue.c":         "int glue;\n",
	}, "x86", nil)

	for _, tc := range []struct{ object, source string }{
		{object: "arch/x86/crypto/aesni-intel.o", source: "arch/x86/crypto/aesni-intel.S"},
		{object: "arch/x86/crypto/glue.o", source: "arch/x86/crypto/glue.c"},
	} {
		variant := variantByTarget(metadata, objectTarget(metadata, config, tc.object))
		if variant.Source != tc.source {
			t.Errorf("%s source = %q, want %q", tc.object, variant.Source, tc.source)
		}
		if variant.Generator != "" {
			t.Errorf("%s acquired generator %q, want none", tc.object, variant.Generator)
		}
		if variant.GeneratedSource != "" {
			t.Errorf("%s acquired generated_source %q, want none", tc.object, variant.GeneratedSource)
		}
	}
}

// TestCompactMetadataIgnoresRecipelessRules pins that drivers/tty/vt's
// "$(obj)/defkeymap.o: $(obj)/defkeymap.c" does not hijack defkeymap.o away
// from its checked-in "_shipped" source.
func TestCompactMetadataIgnoresRecipelessRules(t *testing.T) {
	metadata, config, _ := generatedSourceMetadata(t, "mainmenu \"vt\"\n", map[string]string{
		"Makefile": "obj-y += drivers/tty/vt/\n",
		"drivers/tty/vt/Makefile": `FONTMAPFILE = cp437.uni
obj-y += defkeymap.o consolemap_deftbl.o
hostprogs += conmakehash

quiet_cmd_conmk = CONMK   $@
      cmd_conmk = $(obj)/conmakehash $< > $@

$(obj)/consolemap_deftbl.c: $(src)/$(FONTMAPFILE) $(obj)/conmakehash
	$(call cmd,conmk)

$(obj)/defkeymap.o:  $(obj)/defkeymap.c
`,
		"drivers/tty/vt/cp437.uni":           "# font map\n",
		"drivers/tty/vt/conmakehash.c":       "int main(void) { return 0; }\n",
		"drivers/tty/vt/defkeymap.c_shipped": "int defkeymap;\n",
		"include/linux/types.h":              "\n",
	}, "x86", nil)

	defkeymap := variantByTarget(metadata, objectTarget(metadata, config, "drivers/tty/vt/defkeymap.o"))
	if want := "drivers/tty/vt/defkeymap.c_shipped"; defkeymap.Source != want {
		t.Errorf("defkeymap source = %q, want %q", defkeymap.Source, want)
	}
	if defkeymap.Generator != "" {
		t.Errorf("defkeymap acquired generator %q, want none", defkeymap.Generator)
	}

	// consolemap_deftbl keeps cp437.uni as its source, matching the hardcoded
	// mapping it replaces, and additionally gains the hostprog source as a
	// digest-only input, which nothing invalidated it on before.
	consolemap := variantByTarget(metadata, objectTarget(metadata, config, "drivers/tty/vt/consolemap_deftbl.o"))
	if want := "drivers/tty/vt/cp437.uni"; consolemap.Source != want {
		t.Errorf("consolemap source = %q, want %q", consolemap.Source, want)
	}
}

// TestCompactMetadataKeepsLegacyMappedObjectsOnTheDiskPath pins the
// transitional state deliberately chosen here: rule lookup runs only on the
// on-disk probe's miss path, and sourceCandidatesForObject still maps capflags
// and consolemap_deftbl onto files that exist. So both keep resolving exactly
// as before and never reach the rule resolver.
//
// They migrate when those legacy rows are deleted, which cannot happen until
// the pinned generator release is bumped. TestGeneratedSourceForObjectCapflags
// and TestGeneratedSourceForObjectConsolemap already prove the rule-derived
// path produces the same answers, so the migration is a deletion rather than a
// behaviour change.
func TestCompactMetadataKeepsLegacyMappedObjectsOnTheDiskPath(t *testing.T) {
	metadata, config, _ := generatedSourceMetadata(t, "mainmenu \"capflags\"\n", map[string]string{
		"Makefile": "obj-y += arch/x86/kernel/cpu/\n",
		"arch/x86/kernel/cpu/Makefile": `obj-y += capflags.o

quiet_cmd_mkcapflags = MKCAP   $@
      cmd_mkcapflags = $(CONFIG_SHELL) $(src)/mkcapflags.sh $@ $^

cpufeature = $(src)/../../include/asm/cpufeatures.h
vmxfeature = $(src)/../../include/asm/vmxfeatures.h

$(obj)/capflags.c: $(cpufeature) $(vmxfeature) $(src)/mkcapflags.sh FORCE
	$(call if_changed,mkcapflags)
targets += capflags.c
`,
		"arch/x86/include/asm/cpufeatures.h": "#define X86_FEATURE_FPU (0*32 + 0)\n",
		"arch/x86/include/asm/vmxfeatures.h": "#define VMX_FEATURE_VNMI (0*32 + 0)\n",
		"arch/x86/kernel/cpu/mkcapflags.sh":  "#!/bin/sh\n",
	}, "x86", nil)

	variant := variantByTarget(metadata, objectTarget(metadata, config, "arch/x86/kernel/cpu/capflags.o"))
	if want := "arch/x86/kernel/cpu/mkcapflags.sh"; variant.Source != want {
		t.Errorf("capflags source = %q, want %q", variant.Source, want)
	}
	if variant.Generator != "" {
		t.Errorf("capflags acquired generator %q while the legacy mapping still resolves it", variant.Generator)
	}
}

// TestCompactMetadataStillReportsUnresolvableSources pins that the original
// error survives for objects no rule explains, so the two failures stay
// distinguishable.
func TestCompactMetadataStillReportsUnresolvableSources(t *testing.T) {
	tree := mustParseString(t, "mainmenu \"missing\"\n")
	root := t.TempDir()
	mustWriteSource(t, root, "Makefile", "obj-y += drivers/thing/\n")
	mustWriteSource(t, root, "drivers/thing/Makefile", "obj-y += widget.o\n")
	writeCompactContentGraphForcedInputs(t, root)
	if err := os.MkdirAll(filepath.Join(root, "drivers", "thing"), 0o755); err != nil {
		t.Fatalf("MkdirAll() failed: %v", err)
	}

	kb, err := ParseKbuildDirectoryTree(filepath.Join(root, "Makefile"), KbuildOptions{RootDir: root})
	if err != nil {
		t.Fatalf("ParseKbuildDirectoryTree() failed: %v", err)
	}
	_, err = tree.CompactMetadataBatchWithOptions(
		[]NamedConfig{{Name: "test"}},
		CompactMetadataOptions{
			SourceRoot:            root,
			Srcarch:               "x86",
			CompileEnvironmentABI: "generated-source-abi-v1",
		},
		func(*ResolvedConfig) (CompactConfigGraph, error) {
			return CompactConfigGraph{Kbuild: kb, GeneratedHeadersLabel: "//headers:test"}, nil
		},
	)
	if err == nil {
		t.Fatalf("CompactMetadataBatchWithOptions() succeeded, want an unresolved-source error")
	}
	if want := `exact input scan cannot resolve a source for leaf object "drivers/thing/widget.o"`; !strings.Contains(err.Error(), want) {
		t.Fatalf("error = %v, want it to contain %q", err, want)
	}
}
